export const CONTACT_LOADING = "CONTACT_LOADING";
export const FETCH_CONTACT_LIST = "FETCH_CONTACT_LIST";
export const SAVE_CONTACT_LIST = "SAVE_CONTACT_LIST";
export const CONTACT_ERROR = "CONTACT_ERROR";

export const MESSAGE_LOADING = "MESSAGE_LOADING";
export const FETCH_MESSAGE_LIST = "FETCH_MESSAGE_LIST";
export const SAVE_MESSAGE_LIST = "SAVE_MESSAGE_LIST";
export const MESSAGE_ERROR = "MESSAGE_ERROR";
