export const CONTACT_LOADING = "CONTACT_LOADING";
export const FETCH_CONTACT_LIST = "FETCH_CONTACT_LIST";
export const SAVE_CONTACT_LIST = "SAVE_CONTACT_LIST";
export const CONTACT_ERROR = "CONTACT_ERROR";
